State m_launchBall Isn't Reset (Issue #39)
longwood564/Robot2020 pull request #42
Opened 2021-02-06 17:22 UTC by Tmase13

Set m_launchBall to false in the disabledInit() method.

2021-02-07 19:41 UTC, RyanStyron requested changes
Nice work, just remove the whitespace on line 219. Other than that, it is all good.

2021-02-07 19:41 UTC, RyanStyron commented on src/main/java/frc/robot/Robot.java
> +
Remove whitespace.

2021-02-14 16:55 UTC, RyanStyron commented
Just resolved this issue and merged with upstream changes so that this PR can be closed and merged.

2021-02-14 17:10 UTC, RyanStyron approved these changes

2021-02-14 19:42 UTC, CodingKoopa commented
Looks like there's still a merge conflict.

2021-02-27 16:16 UTC, RyanStyron commented
Closed without merging.

2021-02-27 16:16 UTC, closed without merging